import type { ConnectorTemplate } from './types';

/**
 * The connector catalogue.
 *
 * Ping's ingest endpoint adapts provider payloads server-side, so most of these
 * are now "paste the URL" rather than "build a transform in Zapier first". The
 * `transport` field says which is which, and the copy is expected to match it —
 * claiming parity for a source that genuinely needs a relay (Discord) just
 * wastes someone's afternoon.
 */
export const connectorTemplates: ConnectorTemplate[] = [
  {
    id: 'generic',
    name: 'Any script or service',
    description: 'A webhook URL that accepts plain JSON. Works with curl, cron, CI, Zapier, Make or n8n.',
    icon: 'Webhook',
    transport: 'generic',
    adapterId: 'generic',
    setupSteps: [
      'Copy the webhook URL below — it already contains your channel key and write token.',
      'POST JSON to it. A title is the only required field.',
      'Optionally add body, eventType, severity (0-3) and tags to control the reaction.',
      'Click "Send Test Event" to confirm it arrives.',
    ],
    testEvent: {
      source: 'generic',
      eventType: 'success',
      title: 'Test event from Ping',
      body: 'If you can read this, the webhook works.',
    },
    keywordsSupported: ['success', 'error', 'message', 'thinking', 'warning', 'incident', 'deploy'],
    notes: 'Ping reads the title and body for keywords, so plain English works: "Invoice #204 paid" gets the money reaction with no configuration at all.',
    securityCopy: 'Authenticated by a per-channel write token. It only permits posting events to your own feed, and you can rotate it at any time. All text is redacted server-side — URLs, tokens and code blocks are stripped before storage.',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Pushes, CI results, deployments, issues and pull requests.',
    icon: 'Github',
    transport: 'direct',
    adapterId: 'github',
    setupSteps: [
      'In your repo, go to Settings → Webhooks → Add webhook.',
      'Paste the webhook URL below as the Payload URL.',
      'Set Content type to application/json.',
      'Choose the events you want — pushes, workflow runs, deployments, issues, pull requests.',
      'Save. GitHub sends a test ping immediately and Ping will react to it.',
    ],
    testEvent: {
      source: 'github',
      eventType: 'deploy',
      title: 'Pushed 2 commits to main',
      body: 'feat(ingest): add provider adapters',
    },
    keywordsSupported: ['push', 'deploy', 'ci', 'issue', 'pull request', 'failed'],
    notes: 'No middleware. Ping maps the raw GitHub payload itself: a failed workflow run becomes an error at severity 2, a merged PR reads as a deploy, and events you did not ask about are acknowledged and ignored rather than rejected.',
    securityCopy: 'The write token travels in the URL because GitHub\'s webhook form cannot send custom headers. It is scoped to this channel only. Treat the URL like a password and rotate it if the repo is public.',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payments, subscriptions, invoices and failed charges.',
    icon: 'CreditCard',
    transport: 'direct',
    adapterId: 'stripe',
    setupSteps: [
      'In Stripe, go to Developers → Webhooks → Add endpoint.',
      'Paste the webhook URL below as the endpoint URL.',
      'Select the events you care about, e.g. payment_intent.succeeded and charge.failed.',
      'Save. Use Stripe\'s "Send test webhook" to see Ping react.',
    ],
    testEvent: {
      source: 'stripe',
      eventType: 'success',
      title: 'Payment received: 49.99 USD',
      body: 'payment_intent.succeeded',
    },
    keywordsSupported: ['payment', 'subscription', 'invoice', 'charge', 'refund', 'failed'],
    notes: 'The amount and currency are pulled out into the title, so a successful payment triggers the ka-ching and coin rain. A failed charge or dispute becomes an error — it will not celebrate a payment that did not happen.',
    securityCopy: 'Send only the event types you want visible. Ping stores the amount, currency and event type — never card details, customer emails or raw payloads.',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Deployment success, build failures and cancellations.',
    icon: 'Triangle',
    transport: 'direct',
    adapterId: 'vercel',
    setupSteps: [
      'In Vercel, go to your team or project settings → Webhooks.',
      'Paste the webhook URL below.',
      'Select deployment.succeeded, deployment.error and deployment.canceled.',
      'Save, then trigger a deploy.',
    ],
    testEvent: {
      source: 'vercel',
      eventType: 'deploy',
      title: 'Deployed ping to production',
    },
    keywordsSupported: ['deploy', 'build', 'failed', 'canceled', 'production', 'preview'],
    notes: 'A successful deploy triggers fireworks; a build failure is an error at severity 2 so it reads differently at a glance.',
    securityCopy: 'Ping stores the project name and target environment only. Build logs and environment variables are never sent.',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error alerts and issue notifications.',
    icon: 'Bug',
    transport: 'generic',
    setupSteps: [
      'In Sentry, go to Settings → Alerts → create or edit an alert rule.',
      'Add a webhook action pointing at the URL below.',
      'Alternatively use Settings → Integrations → Webhooks for issue-level events.',
      'Trigger a test error to confirm it arrives.',
    ],
    testEvent: {
      source: 'sentry',
      eventType: 'incident',
      title: 'TypeError in api/users.ts',
      body: 'Cannot read properties of undefined',
    },
    keywordsSupported: ['error', 'exception', 'crash', 'incident', 'resolved', 'regression'],
    notes: 'A dedicated Sentry adapter is coming. Until then Sentry\'s payload still lands as an event — the keyword routing reads "error" and "exception" from the text and reacts correctly. Set severity to 3 on the alert payload if you want it to override everything else.',
    securityCopy: 'Stack traces are long and often contain paths and tokens. Ping stores a truncated title and body with URLs, tokens and code blocks redacted server-side.',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Issue and project updates from your team\'s workflow.',
    icon: 'SquareKanban',
    transport: 'generic',
    setupSteps: [
      'In Linear, go to Settings → API → Webhooks → New webhook.',
      'Paste the webhook URL below.',
      'Select the events you want: issues, comments, projects.',
      'Save and change an issue to test it.',
    ],
    testEvent: {
      source: 'linear',
      eventType: 'message',
      title: 'ENG-142 moved to In Progress',
      body: 'Fix auth token refresh',
    },
    keywordsSupported: ['issue', 'bug', 'blocked', 'done', 'assigned', 'in progress'],
    notes: 'A dedicated Linear adapter is coming. Linear\'s payload already carries readable text, so keyword routing handles it: "done" celebrates, "bug" and "blocked" read as warnings.',
    securityCopy: 'Issue titles may contain internal details. Everything is redacted server-side and Ping stores only what it displays.',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Messages, mentions and alerts from your workspace.',
    icon: 'MessageSquare',
    transport: 'middleware',
    setupSteps: [
      'Slack needs a Slack app, not just a URL — outbound webhooks alone will not do it.',
      'Create an app at api.slack.com, enable Event Subscriptions and point it at the URL below.',
      'Slack sends a url_verification challenge first; Ping answers it automatically.',
      'Subscribe to the message events you want, then install the app to your workspace.',
      'Simplest alternative: a Zapier or Make step that forwards matching messages as JSON.',
    ],
    testEvent: {
      source: 'slack',
      eventType: 'message',
      title: 'New message in #general',
      body: 'heads up, deploy going out in 10',
    },
    keywordsSupported: ['message', 'mention', 'thread', 'alert', 'channel'],
    notes: 'More setup than the others because Slack requires an app with event subscriptions. Worth filtering hard — an unfiltered channel will make Ping react constantly.',
    securityCopy: 'Never give Ping a Slack bot token. It only needs the events forwarded to its URL. Filter at the Slack end so private conversations are never sent.',
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Server events — needs a bot or relay, not just a URL.',
    icon: 'Gamepad2',
    transport: 'middleware',
    setupSteps: [
      'Discord webhooks are inbound only: they post INTO Discord, not out of it.',
      'So there is no URL to paste — something has to forward events on your behalf.',
      'Use a bot with the message intent, or a Zapier/Make Discord trigger.',
      'Have it POST JSON to the webhook URL below with a title and body.',
    ],
    testEvent: {
      source: 'discord',
      eventType: 'message',
      title: 'Message in #announcements',
      body: 'New release v2.1.0 is live',
    },
    keywordsSupported: ['message', 'join', 'leave', 'alert', 'bot', 'announcement'],
    notes: 'The only connector here that genuinely cannot be a paste-the-URL setup. That is a Discord limitation, not a Ping one.',
    securityCopy: 'Never expose a Discord bot token to Ping. The relay keeps the token; Ping only receives the text you choose to forward.',
  },
  {
    id: 'openclaw',
    name: 'Local bridge',
    description: 'Connect a local agent or script over a WebSocket on your own machine.',
    icon: 'Bot',
    transport: 'bridge',
    setupSteps: [
      'Start a bridge that listens on ws://127.0.0.1:3939/ping.',
      'OpenClaw ships one: npx openclaw@latest start --bridge.',
      'In Ping, open Bridge and connect to that URL.',
      'Any local process that speaks the ping/0.1 protocol works — OpenClaw is one example.',
    ],
    testEvent: {
      source: 'bridge',
      eventType: 'success',
      title: 'Bridge connected',
      body: 'A local process is sending events to Ping.',
    },
    keywordsSupported: ['message', 'thinking', 'speaking', 'error'],
    notes: 'The only transport that is not HTTP. Useful when you want events to stay on your machine, or when the source is a local script rather than a hosted service.',
    securityCopy: 'The bridge runs on localhost, so nothing leaves your machine and no events are stored in the cloud. Ping only accepts ws:// and wss:// URLs.',
  },
];
