import type { ConnectorTemplate } from './types';

export const connectorTemplates: ConnectorTemplate[] = [
  {
    id: 'openclaw',
    name: 'OpenClaw',
    description: 'Connect a local AI agent to Ping over WebSocket. The primary way to give your agent a face.',
    icon: 'Bot',
    setupSteps: [
      'Install OpenClaw: npx openclaw@latest',
      'Start the bridge: npx openclaw start',
      'In Ping, open Bridge and connect to ws://127.0.0.1:3939/ping',
      'Your agent can now send emotions, expressions, and messages to Ping in real time.',
    ],
    testEvent: {
      source: 'openclaw',
      eventType: 'success',
      title: 'Bridge connected',
      body: 'OpenClaw agent is live and sending events to Ping.',
    },
    keywordsSupported: ['emotion', 'expression', 'speak', 'think', 'react', 'spectacle'],
    notes: 'OpenClaw is the recommended way to connect AI agents. It uses a local WebSocket bridge, so your data never leaves your machine.',
    securityCopy: 'All communication stays on your local network. No data is sent to external servers. The bridge runs on localhost only.',
  },
  {
    id: 'generic',
    name: 'Generic Webhook',
    description: 'Send events from any HTTP-capable service — scripts, Zapier, Make, n8n, or curl.',
    icon: 'Webhook',
    setupSteps: [
      'Copy the Ingest URL below (includes your channel key).',
      'Set the x-ping-secret header to your ingest secret.',
      'POST a JSON payload matching the schema shown below.',
      'Click "Send Test Event" to verify the connection.',
    ],
    testEvent: {
      source: 'generic',
      eventType: 'success',
      title: 'Test event from Generic connector',
      body: 'Hello from the Generic webhook!',
    },
    keywordsSupported: ['success', 'error', 'message', 'thinking', 'warning', 'incident', 'deploy'],
    notes: 'Works with any service that can make HTTP POST requests. No middleware needed.',
    securityCopy: 'Events are authenticated via shared secret or HMAC-SHA256 signature. All text fields are redacted server-side (URLs, tokens, code blocks stripped).',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Get payment and subscription notifications — see Ping react to revenue events.',
    icon: 'CreditCard',
    setupSteps: [
      'Option A (Recommended): Use Zapier or Make to forward Stripe events to Ping.',
      'In Zapier/Make, create a Stripe trigger (e.g., "Payment Succeeded").',
      'Map the event to Ping\'s JSON schema: set eventType to "success" and include $ amounts in body.',
      'Set the webhook URL to the Ingest URL below with x-ping-secret header.',
      'Option B (Advanced): Point Stripe webhooks directly at the Ingest URL and transform payloads via a middleware function.',
    ],
    testEvent: {
      source: 'stripe',
      eventType: 'success',
      title: 'Payment succeeded',
      body: 'Order #1234 — $49.99 from customer@email.com',
    },
    keywordsSupported: ['payment', 'subscription', 'invoice', '$', 'charge'],
    notes: 'Money keywords ($, payment, invoice) trigger the sparkle trail + cheer reaction. Subscription events trigger success reactions.',
    securityCopy: 'Never send raw Stripe webhook secrets to Ping. Use a middleware (Zapier/Make) to transform and forward only the fields you want. Ping redacts URLs and tokens automatically.',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'React to pushes, deployments, and issues — see Ping celebrate your deploys.',
    icon: 'Github',
    setupSteps: [
      'In your GitHub repo, go to Settings → Webhooks → Add webhook.',
      'Set the Payload URL to the Ingest URL below.',
      'Set Content type to application/json.',
      'Add x-ping-secret as a custom header with your ingest secret value.',
      'Select events: Pushes, Deployments, Issues (or "Send me everything").',
      'Use Zapier/Make as middleware to map GitHub payloads to Ping\'s JSON schema.',
    ],
    testEvent: {
      source: 'github',
      eventType: 'deploy',
      title: 'Deployed to production',
      body: 'main branch shipped — build #42 succeeded',
    },
    keywordsSupported: ['deploy', 'shipped', 'push', 'issue', 'pull request', 'build'],
    notes: 'Deploy keywords trigger fireworks + proud reaction. Issue events map to message/warning. Use Zapier/Make for the cleanest experience.',
    securityCopy: 'GitHub sends a signature header (X-Hub-Signature-256). For direct integration, you\'d verify this server-side. Using Zapier/Make as middleware is simpler and recommended for Stage 2.',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Surface messages, mentions, and alerts — Ping reacts to your team\'s Slack activity.',
    icon: 'MessageSquare',
    setupSteps: [
      'Use Zapier or Make to forward Slack events to Ping.',
      'Create a Slack trigger (e.g., "New Message in Channel" or "New Mention").',
      'Map the event to Ping\'s JSON schema: set eventType to "message" and include the message text in body.',
      'Set the webhook URL to the Ingest URL below with x-ping-secret header.',
    ],
    testEvent: {
      source: 'slack',
      eventType: 'message',
      title: 'New message in #general',
      body: '@team heads up — deploy going out in 10 min',
    },
    keywordsSupported: ['message', 'mention', 'thread', 'alert', 'channel'],
    notes: 'Message keywords trigger the default chat reaction. Use Zapier/Make to filter which channels or keywords forward to Ping.',
    securityCopy: 'Use Zapier/Make as middleware — never expose your Slack Bot Token directly. Ping redacts URLs and tokens automatically.',
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Get notified on server events — messages, member joins, and bot alerts.',
    icon: 'Gamepad2',
    setupSteps: [
      'Use Zapier, Make, or a Discord bot to forward events to Ping.',
      'Create a trigger for the events you want (e.g., "New Message", "Member Joined").',
      'Map the event to Ping\'s JSON schema: set eventType to "message" and include content in body.',
      'Set the webhook URL to the Ingest URL below with x-ping-secret header.',
    ],
    testEvent: {
      source: 'discord',
      eventType: 'message',
      title: 'Message in #announcements',
      body: 'New release v2.1.0 is live! 🎉',
    },
    keywordsSupported: ['message', 'join', 'leave', 'alert', 'bot', 'announcement'],
    notes: 'Join/leave events can trigger success/warning reactions. Announcement keywords trigger the notify sound.',
    securityCopy: 'Use middleware to forward events — never expose Discord bot tokens to Ping. All text fields are redacted server-side.',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Track issues and project updates — see Ping react to your team\'s workflow.',
    icon: 'SquareKanban',
    setupSteps: [
      'In Linear, go to Settings → API → Webhooks → New webhook.',
      'Set the URL to the Ingest URL below.',
      'Select the events you want: Issue created, Issue updated, Comment created, etc.',
      'Use Zapier/Make to transform Linear payloads to Ping\'s JSON schema, or build a small middleware.',
    ],
    testEvent: {
      source: 'linear',
      eventType: 'message',
      title: 'Issue ENG-142 moved to In Progress',
      body: 'Fix auth token refresh — assigned to @alice',
    },
    keywordsSupported: ['issue', 'bug', 'feature', 'in progress', 'done', 'blocked', 'assigned'],
    notes: '"Done" keywords trigger success reactions. "Bug" and "blocked" trigger warning/incident reactions.',
    securityCopy: 'Linear sends a webhook signature for verification. Use middleware to validate and forward only the fields you need.',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Monitor errors and crashes — Ping reacts to production issues in real time.',
    icon: 'Bug',
    setupSteps: [
      'In Sentry, go to Settings → Integrations → Webhooks (or use Zapier/Make).',
      'Set the webhook URL to the Ingest URL below.',
      'Map Sentry alerts to Ping\'s schema: set eventType to "error" or "incident" and include the error message in body.',
      'Add the x-ping-secret header with your ingest secret value.',
    ],
    testEvent: {
      source: 'sentry',
      eventType: 'error',
      title: 'TypeError in api/users.ts',
      body: 'Cannot read properties of undefined (reading \'id\') — 42 events in the last hour',
    },
    keywordsSupported: ['error', 'exception', 'crash', 'incident', 'resolved', 'regression'],
    notes: 'Error/incident keywords trigger the alarm reaction with the error sound. "Resolved" triggers a success celebration.',
    securityCopy: 'Sentry can sign webhook payloads. Verify signatures server-side or use Zapier/Make as middleware for simplicity.',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Celebrate deploys and catch build failures — see Ping react to your CI/CD pipeline.',
    icon: 'Triangle',
    setupSteps: [
      'In Vercel, go to Project Settings → Git → Deploy Hooks, or use Integration Webhooks.',
      'Set the webhook URL to the Ingest URL below.',
      'Use Zapier/Make to map Vercel deployment payloads to Ping\'s JSON schema.',
      'Set eventType to "deploy" for successful deploys or "error" for build failures.',
    ],
    testEvent: {
      source: 'vercel',
      eventType: 'deploy',
      title: 'Deployed to production',
      body: 'ping-app — commit abc1234 built in 38s',
    },
    keywordsSupported: ['deploy', 'build', 'shipped', 'failed', 'preview', 'production'],
    notes: 'Deploy keywords trigger fireworks + proud reaction. Build failure keywords trigger the error alarm.',
    securityCopy: 'Vercel signs webhook payloads with a secret. Verify server-side or use middleware. Ping redacts URLs and tokens automatically.',
  },
];
